// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.CodeAnalysis.Testing;
using Xunit;

namespace Swick.Features.Generator.Tests;

public class FeaturesGeneratorTests
{
    [Fact]
    public async Task Empty()
    {
        var test = string.Empty;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { test },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task OnlyOneServiceCanBeRegistered()
    {
        const string Test = """
            using Swick.Features;
            using System.Threading;

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public class TestImpl2 : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                [{|#0:Register(typeof(ITest), typeof(TestImpl2))|}]
                private partial T Get<T>();
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private partial T? Get<T>()
                {
                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(KnownErrors.DuplicateService).WithLocation(0),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task DifferentGenericParameter()
    {
        const string Test = """
            using Swick.Features;
            using System.Threading;

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public class TestImpl2 : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                private partial TFeature Get<TFeature>();
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private global::Test.ITest? _TestImpl;
            
                private partial TFeature? Get<TFeature>()
                {
                    if (typeof(TFeature) == typeof(global::Test.ITest))
                    {
                        if (_TestImpl is null)
                        {
                            _TestImpl = new global::Test.TestImpl();
                        }

                        return (TFeature)_TestImpl;
                    }

                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task InvalidMethodParameters()
    {
        const string Test = """
            using Swick.Features;
            using System.Threading;

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public class TestImpl2 : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                private partial T {|#0:Get|}<T>(string i);
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                // Invalid get method
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(KnownErrors.InvalidGenericGetMethod).WithLocation(0),
                    DiagnosticResult.CompilerError("CS8795").WithArguments("Test.Factory.Get<T>(string)").WithLocation(0),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task NoGenericParameter()
    {
        const string Test = """
            using Swick.Features;
            using System.Threading;

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                private partial int {|#0:Get|}();
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                // Invalid get method
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(KnownErrors.InvalidGenericGetMethod).WithLocation(0),
                    DiagnosticResult.CompilerError("CS8795").WithArguments("Test.Factory.Get()").WithLocation(0),
                },
            },
        }.RunAsync();
    }


    [Fact]
    public async Task InvalidReturnOnGetMethod()
    {
        const string Test = """
            using Swick.Features;
            using System.Threading;

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                private partial int {|#0:Get|}<T>();
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                // Invalid get method
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(KnownErrors.InvalidGenericGetMethod).WithLocation(0),
                    DiagnosticResult.CompilerError("CS8795").WithArguments("Test.Factory.Get<T>()").WithLocation(0),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task SettingInvalidArg1()
    {
        const string Test = """
            using Swick.Features;
            using System.Threading;

            #nullable enable

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public class TestImpl2 : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                [{|#0:ContainerOptions(SetMethod = nameof(Set))|}]
                private partial TFeature? Get<TFeature>();

                partial bool {|#1:Set|}(string? feature);
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private partial TFeature? Get<TFeature>()
                {
                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(KnownErrors.InvalidSetMethod).WithLocation(0),
                    DiagnosticResult.CompilerError("CS8796").WithLocation(1).WithArguments("Test.Factory.Set(string?)"),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task SettingInvalidArg2()
    {
        const string Test = """
            using Swick.Features;
            using System.Threading;

            #nullable enable

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public class TestImpl2 : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                [{|#0:ContainerOptions(SetMethod = nameof(Set))|}]
                private partial TFeature? Get<TFeature>();

                partial void Set(string? feature);
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private partial TFeature? Get<TFeature>()
                {
                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(KnownErrors.InvalidSetMethod).WithLocation(0),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task SetterBooleanReturn()
    {
        const string Test = """
            using Swick.Features;
            using System.Threading;

            #nullable enable

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public class TestImpl2 : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                [ContainerOptions(SetMethod = nameof(Set))]
                private partial TFeature? Get<TFeature>();

                private partial bool Set<TFeature>(TFeature? feature);
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private global::Test.ITest? _TestImpl;
            
                private partial TFeature? Get<TFeature>()
                {
                    if (typeof(TFeature) == typeof(global::Test.ITest))
                    {
                        if (_TestImpl is null)
                        {
                            _TestImpl = new global::Test.TestImpl();
                        }

                        return (TFeature)_TestImpl;
                    }

                    return default;
                }
            
                private partial bool Set<TFeature>(TFeature? feature)
                {
                    if (typeof(TFeature) == typeof(global::Test.ITest))
                    {
                        _TestImpl = (global::Test.ITest?)(object?)feature;
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task SetterNoBooleanReturn()
    {
        const string Test = """
            using Swick.Features;
            using System.Threading;

            #nullable enable

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public class TestImpl2 : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                [ContainerOptions(SetMethod = nameof(Set))]
                private partial TFeature? Get<TFeature>();

                private partial void Set<TFeature>(TFeature? feature);
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private global::Test.ITest? _TestImpl;
            
                private partial TFeature? Get<TFeature>()
                {
                    if (typeof(TFeature) == typeof(global::Test.ITest))
                    {
                        if (_TestImpl is null)
                        {
                            _TestImpl = new global::Test.TestImpl();
                        }

                        return (TFeature)_TestImpl;
                    }

                    return default;
                }
            
                private partial void Set<TFeature>(TFeature? feature)
                {
                    if (typeof(TFeature) == typeof(global::Test.ITest))
                    {
                        _TestImpl = (global::Test.ITest?)(object?)feature;
                    }
                    else
                    {
                        throw new global::System.NotSupportedException();
                    }
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task SetterBooleanReturnThreadSafe()
    {
        const string Test = """
            using Swick.Features;
            using System.Threading;

            #nullable enable

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public class TestImpl2 : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                [ContainerOptions(IsThreadSafe = true, SetMethod = nameof(Set))]
                private partial TFeature? Get<TFeature>();

                private partial bool Set<TFeature>(TFeature? feature);
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            using System.Threading;

            namespace Test;

            public partial class Factory
            {
                private global::Test.ITest? _TestImpl;
            
                private partial TFeature? Get<TFeature>()
                {
                    if (typeof(TFeature) == typeof(global::Test.ITest))
                    {
                        if (_TestImpl is null)
                        {
                            Interlocked.CompareExchange(ref _TestImpl, new global::Test.TestImpl(), null);
                        }

                        return (TFeature)_TestImpl;
                    }

                    return default;
                }
            
                private partial bool Set<TFeature>(TFeature? feature)
                {
                    if (typeof(TFeature) == typeof(global::Test.ITest))
                    {
                        Interlocked.Exchange(ref _TestImpl, (global::Test.ITest?)(object?)feature);
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task FactoryWithIncorrectReturn()
    {
        const string Test = """
            using Swick.Features;

            namespace Test;

            public interface ITest
            {
            }

            public interface ITest2
            {
            }

            public partial class Factory
            {
                [{|#0:RegisterFactory(typeof(ITest), nameof(SomeFactory))|}]
                private partial T Get<T>();

                private ITest2 SomeFactory() => default;
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private partial T? Get<T>()
                {
                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(KnownErrors.InvalidFactory).WithLocation(0),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task FactoryWithParameters()
    {
        const string Test = """
            using Swick.Features;

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public partial class Factory
            {
                [{|#0:RegisterFactory(typeof(ITest), nameof(SomeFactory))|}]
                private partial T Get<T>();

                private ITest SomeFactory(int i) => default;
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private partial T? Get<T>()
                {
                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(KnownErrors.InvalidFactory).WithLocation(0),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task NonexistentFactory()
    {
        const string Test = """
            using Swick.Features;

            namespace Test;

            public interface ITest
            {
            }

            public partial class Factory
            {
                [{|#0:RegisterFactory(typeof(ITest), "SomeFactory")|}]
                private partial T Get<T>();
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private partial T? Get<T>()
                {
                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(KnownErrors.InvalidFactory).WithLocation(0),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task DuplicateKnown()
    {
        const string Test = """
            using Swick.Features;

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                [{|#0:Register(typeof(ITest), typeof(TestImpl))|}]
                private partial T Get<T>();
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private partial T? Get<T>()
                {
                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
                ExpectedDiagnostics =
                {
                    DiagnosticResult.CompilerError(KnownErrors.DuplicateService).WithLocation(0),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task ConcreteOnly()
    {
        var test = """
            using Swick.Features;

            namespace Test;

            public class TestImpl
            {
            }

            public partial class Factory
            {
                [Register(typeof(TestImpl))]
                private partial T Get<T>();
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private global::Test.TestImpl? _TestImpl;

                private partial T? Get<T>()
                {
                    if (typeof(T) == typeof(global::Test.TestImpl))
                    {
                        if (_TestImpl is null)
                        {
                            _TestImpl = new global::Test.TestImpl();
                        }

                        return (T)(object)_TestImpl;
                    }

                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task ConcreteOnlyThreadSafe()
    {
        const string Test = """
            using Swick.Features;

            namespace Test;

            public class TestImpl
            {
            }

            public partial class Factory
            {
                [Register(typeof(TestImpl))]
                [ContainerOptions(IsThreadSafe = true)]
                private partial T Get<T>();
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            using System.Threading;

            namespace Test;

            public partial class Factory
            {
                private global::Test.TestImpl? _TestImpl;

                private partial T? Get<T>()
                {
                    if (typeof(T) == typeof(global::Test.TestImpl))
                    {
                        if (_TestImpl is null)
                        {
                            Interlocked.CompareExchange(ref _TestImpl, new global::Test.TestImpl(), null);
                        }

                        return (T)(object)_TestImpl;
                    }

                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task SingleGeneratorNestedClass()
    {
        var test = @"using Swick.Features;

namespace Test;

public interface ITest
{
}

public class TestImpl : ITest
{
}

public partial class Factory
{
    private partial class Other
    {
        [Register(typeof(ITest), typeof(TestImpl))]
        [ContainerOptions(IsThreadSafe = true)]
        private partial T Get<T>();
    }
}";
        const string Created = """
            // <auto-generated/>

            #nullable enable

            using System.Threading;

            namespace Test;

            public partial class Factory
            {
                private partial class Other
                {
                    private global::Test.ITest? _TestImpl;

                    private partial T? Get<T>()
                    {
                        if (typeof(T) == typeof(global::Test.ITest))
                        {
                            if (_TestImpl is null)
                            {
                                Interlocked.CompareExchange(ref _TestImpl, new global::Test.TestImpl(), null);
                            }

                            return (T)_TestImpl;
                        }

                        return default;
                    }
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Other.Get.cs", Created),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task SingleGenerator()
    {
        var test = """
            using Swick.Features;

            using System.Threading;

            namespace Test;

            public interface ITest
            {
            }

            public class TestImpl : ITest
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest), typeof(TestImpl))]
                [ContainerOptions(IsThreadSafe = true)]
                private partial T Get<T>();
            }
            """;
        var created = """
            // <auto-generated/>

            #nullable enable

            using System.Threading;

            namespace Test;

            public partial class Factory
            {
                private global::Test.ITest? _TestImpl;

                private partial T? Get<T>()
                {
                    if (typeof(T) == typeof(global::Test.ITest))
                    {
                        if (_TestImpl is null)
                        {
                            Interlocked.CompareExchange(ref _TestImpl, new global::Test.TestImpl(), null);
                        }

                        return (T)_TestImpl;
                    }

                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", created),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task SingleGeneratorMultipleServices()
    {
        const string Test = """
            using Swick.Features;

            namespace Test;

            public interface ITest1
            {
            }

            public class TestImpl1 : ITest1
            {
            }

            public interface ITest2
            {
            }

            public class TestImpl2 : ITest2
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest1), typeof(TestImpl1))]
                [Register(typeof(ITest2), typeof(TestImpl2))]
                [ContainerOptions(IsThreadSafe = true)]
                private partial T Get<T>();
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            using System.Threading;

            namespace Test;

            public partial class Factory
            {
                private global::Test.ITest1? _TestImpl1;
                private global::Test.ITest2? _TestImpl2;

                private partial T? Get<T>()
                {
                    if (typeof(T) == typeof(global::Test.ITest1))
                    {
                        if (_TestImpl1 is null)
                        {
                            Interlocked.CompareExchange(ref _TestImpl1, new global::Test.TestImpl1(), null);
                        }

                        return (T)_TestImpl1;
                    }

                    if (typeof(T) == typeof(global::Test.ITest2))
                    {
                        if (_TestImpl2 is null)
                        {
                            Interlocked.CompareExchange(ref _TestImpl2, new global::Test.TestImpl2(), null);
                        }

                        return (T)_TestImpl2;
                    }

                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task SingleGeneratorMultipleServicesNotThreadSafe()
    {
        const string Test = """
            using Swick.Features;

            namespace Test;

            public interface ITest1
            {
            }

            public class TestImpl1 : ITest1
            {
            }

            public interface ITest2
            {
            }

            public class TestImpl2 : ITest2
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest1), typeof(TestImpl1))]
                [Register(typeof(ITest2), typeof(TestImpl2))]
                private partial T Get<T>();
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private global::Test.ITest1? _TestImpl1;
                private global::Test.ITest2? _TestImpl2;

                private partial T? Get<T>()
                {
                    if (typeof(T) == typeof(global::Test.ITest1))
                    {
                        if (_TestImpl1 is null)
                        {
                            _TestImpl1 = new global::Test.TestImpl1();
                        }

                        return (T)_TestImpl1;
                    }

                    if (typeof(T) == typeof(global::Test.ITest2))
                    {
                        if (_TestImpl2 is null)
                        {
                            _TestImpl2 = new global::Test.TestImpl2();
                        }

                        return (T)_TestImpl2;
                    }

                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
            },
        }.RunAsync();
    }

    [Fact]
    public async Task SingleGeneratorFactoryMethod()
    {
        const string Test = """
            using Swick.Features;

            namespace Test;

            public interface ITest1
            {
            }

            public class TestImpl1 : ITest1
            {
            }

            public interface ITest2
            {
            }

            public class TestImpl2 : ITest2
            {
            }

            public partial class Factory
            {
                [Register(typeof(ITest1), typeof(TestImpl1))]
                [RegisterFactory(typeof(ITest2), nameof(CreateTest2))]
                private partial T Get<T>();

                private ITest2 CreateTest2() => new TestImpl2();
            }
            """;
        const string Created = """
            // <auto-generated/>

            #nullable enable

            namespace Test;

            public partial class Factory
            {
                private global::Test.ITest1? _TestImpl1;
                private global::Test.ITest2? _ITest2;

                private partial T? Get<T>()
                {
                    if (typeof(T) == typeof(global::Test.ITest1))
                    {
                        if (_TestImpl1 is null)
                        {
                            _TestImpl1 = new global::Test.TestImpl1();
                        }

                        return (T)_TestImpl1;
                    }

                    if (typeof(T) == typeof(global::Test.ITest2))
                    {
                        if (_ITest2 is null)
                        {
                            _ITest2 = CreateTest2();
                        }

                        return (T)_ITest2;
                    }

                    return default;
                }
            }

            """;

        await new FeaturesVerifier
        {
            TestState =
            {
                Sources = { Test },
                GeneratedSources =
                {
                    (typeof(FeaturesGenerator), "Test.Factory.Get.cs", Created),
                },
            },
        }.RunAsync();
    }
}

